version: "2.0"

services:
  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: "backoffice"
      POSTGRES_PASSWORD: "KMp7mMnfgOws2BYw"
      POSTGRES_DB: "backoffice"
    ports:
      - "5432:5432"