workedtimesendtime: 00 56 18 * * *
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: @gmail.com
    password:

  issuesearchparams:
    jql: project = "CRA" AND Sprint = "24"
    options:
      startat: 0
      maxresults: 1000
      validatequery: strict
      fields:
      - customfield_10010
      - timespent
      - timeoriginalestimate
      - summary
      - status
      - issuetype

slack:
  apiurl: https://slack.com/api
  auth:
    intoken:
    outtoken:

  channel:
    id: leads-bot-development
    botname: Back Office Bot

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token:
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login: @gmail.com
    password:

  orgsid: 60470