ginport: 1234

dailyreportcrontime: "00 00 07 * * *"
weeklyreportcrontime: "00 00 07 * * *"
tasktimeexceedionreportcrontime: "@every 1h"
gittoken:
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: b0s.at.works@gmail.com
    password: 9a0a6d53724cbdda0eee6e59d01abea1

slack:
  apiurl: https://slack.com/api
  auth:
    intoken: ITYgHVRVRhOIZfvDpVgCS6CM
    outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79

  channel:
    migrationsid: migrations
    backofficeappid: back-office-app
    botname: Back Office Bot

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: 9mNJD2Jfom7FCwvvjlil8OP6pSb6bfKUZDDYmK-J2uE
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login: b0s.at.works@gmail.com
    password: ckhw1yr6ne7g90rn5ocdt4hdnext3nhi
  orgsid: 60470