workedtimesendtime: 00 56 18 * * *
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: b0s.at.works@gmail.com
    password: 9a0a6d53724cbdda0eee6e59d01abea1

slack:
  apiurl: https://slack.com/api
  auth:
    intoken: ITYgHVRVRhOIZfvDpVgCS6CM
    outtoken: xoxp-350508480163-349912767072-369584053265-53086c6f7643871d6ab6c4eda69e5ebc

  channel:
    id: leads-bot-development
    botname: Back Office Bot

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: 9mNJD2Jfom7FCwvvjlil8OP6pSb6bfKUZDDYmK-J2uE
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login: b0s.at.works@gmail.com
    password: ckhw1yr6ne7g90rn5ocdt4hdnext3nhi
  orgsid: 60470