loglevel: debug
ginport: 1234
gindebugmode: true
cron:
  dailyworkersworkedtime: "00 00 07 * * *"
  weeklyworkersworkedtime: "00 00 07 * * 1"
  reportclosedsubtasks: "00 00 07 * * *"
  reportaftersecondreview: "00 00 07 * * *"
  employeesexceededtasks: "00 00 07 * * *"
  reportgitmigrations: "@hourly"
gittoken:
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username:
    password:

bitbucket:
  apiurl: https://api.bitbucket.org/2.0
  owner: theflowglobal
  auth:
    username:
    password:

slack:
  apiurl: https://slack.com/api
  chanbackofficeapp: back-office-app
  chanmigrations: migrations
  botname: Back Office Bot
  intoken: ITYgHVRVRhOIZfvDpVgCS6CM
  outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: 9omAc5EjhHp7wKXfqBCunHri6jkOsn_FFCcPC8XOqZo
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login:
    password:
  orgsid: 60470