loglevel: debug
ginport: 1234
gindebugmode: true
maxweekworkinghours: 30.0
reports:
  dailyworkersworkedtime:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  weeklyworkersworkedtime:
    schedule: "00 00 07 * * 1"
    channel: "#back-office-app"
  reportclosedsubtasks:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  reportaftersecondreview:
    schedule: "00 00 07 * * *"
    channel: "U891K2Z2P"
  employeesexceededtasks:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  employeesexceededestimatetime:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  reportslackspaceending:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  reportgitmigrations:
    schedule: "@hourly"
    channel: "#migrations"
  reportsprintstatus:
    schedule: "00 00 05 * * MON"
    channel: "#general"
  reportclarificationissues:
    schedule: "00 00 07 * * *"
  reportlongtimereviewissues:
    schedule: "00 00 07 * * *"

jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username:
    password:

bitbucket:
  apiurl: https://api.bitbucket.org/2.0
  owner: theflowglobal
  auth:
    username:
    password:

slack:
  apiurl: https://slack.com/api
  botname: Back Office Bot
  projectmanager: U9FDU5W4D
  intoken: xoxp-281270780213-532563372454-545645521588-6e70abc49c386bb1ad94465d19866188
  outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79
  totalVolume: 5.0
  restVolume: 0.0
  secret: 046b6a43f79bca89a7f9056921906b25
  ignorelist:
    - 'Pavel Palenin'
    - 'Oleg Raev'
    - 'Rodion Golovushkin'
    - 'Ivan Tomilov'
    - 'Former user'

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: 9omAc5EjhHp7wKXfqBCunHri6jkOsn_FFCcPC8XOqZo
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login:
    password:
  orgsid: 60470