loglevel: debug
ginport: 1234
gindebugmode: true
maxweekworkinghours: 30.0
reports:
  dailyworkersworkedtime:
    schedule: "@yearly"
    channel: "#work-reports"
  weeklyworkersworkedtime:
    schedule: "@yearly"
    channel: "#work-reports"
  reportclosedsubtasks:
    schedule: "@yearly"
    channel: "#back-office-app"
  reportaftersecondreviewall:
    schedule: "@yearly"
    channel: "Ivan Tomilov"
  reportaftersecondreviewbe:
    schedule: "@yearly"
    channel: "Oleg Raev"
  reportaftersecondreviewfe:
    schedule: "@yearly"
    channel: "Rodion Golovushkin"
  employeesexceededtasks:
    schedule: "@yearly"
    channel: "#back-office-app"
  reportslackspaceending:
    schedule: "@yearly"
    channel: "#back-office-app"
  reportgitmigrations:
    schedule: "@hourly"
    channel: "#migrations"
  reportsprintstatus:
    schedule: "@yearly"
    channel: "#general"
  reportclarificationissues:
    schedule: "@yearly"
  report24hoursreviewissues:
    schedule: "@yearly"
  reportgitansiblechanges:
    schedule: "@yearly"
    channel: "Denis Yudin"
  dailyworkerslessworkedmessage:
    schedule: "@yearly"
    channel: "#managers"
  weeklyreportoverworkedissues:
    schedule: "@yearly"
    channel: "Artem Efremov"
  reportepicclosedissues:
    schedule: "@yearly"
    channel: "#back-office-app"

jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: stepan.morozov@atnr.pro
    token: GaQ1oimS8bWXNdqcFyRG492D

bitbucket:
  apiurl: https://api.bitbucket.org/2.0
  owner: atnrpro
  auth:
    username: stepan.morozov@atnr.pro
    password: 123123123

slack:
  apiurl: https://slack.com/api
  botname: Back Office Bot
  intoken: xoxp-281270780213-532563372454-545645521588-6e70abc49c386bb1ad94465d19866188
  outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79
  totalVolume: 5.0
  restVolume: 0.0
  secret: 27f79262fd9f22a1db80a4fd70b2374a
  employees:
    directorofcompany: U891K2Z2P
    projectmanager: U9FDU5W4D
    artdirector: U89802W2Z
    teamleaderbe: U97DJLL11
    teamleaderfe: U88K5BQAD
    beteam:
      - 'Morozov Stepan'
      - 'Arthur Danilevskiy'
      - 'Roman Vlasenko'
      - 'Muzafar Muradov'
    feteam:
      - 'Andrey Solovyov'
      - 'Denis Kolosov'
  ignorelist:
    - 'Pavel Palenin'
    - 'Oleg Raev'
    - 'Rodion Golovushkin'
    - 'Ivan Tomilov'
    - 'Former user'

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: 9omAc5EjhHp7wKXfqBCunHri6jkOsn_FFCcPC8XOqZo
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login:
    password:
  orgsid: 60470

database:
  name: backoffice
  host: localhost
  port: 5432
  user: backoffice
  password: KMp7mMnfgOws2BYw
  enable_ssl: false

amplify:
  notifychannelid: CKBT66G5A
  channelstag: '#test-backoffice-bot'
  channelprod: '#test-backoffice-bot'
  mention:
    - UFNGKAYDC

users:
  - jiraaccountid: 5a2575776a747c0e71ab2972
    email: andrey.solovyov@atnr.pro
    slackid: U8990009Z
    slackname: tinymail8
    slackrealname: "Andrey Solovyov"

  - jiraaccountid: 5acf07e953a71a2a7cd8657f
    email: artem.efremov@atnr.pro
    slackid: U9FDU5W4D
    slackname: drmroll
    slackrealname: "Artem Efremov"

  - jiraaccountid: "557058:00cb683a-68e2-49a8-a727-96e2494e5160"
    email: arthur.danilevskiy@atnr.pro
    slackid: U9ALLBG5S
    slackname: arthurdanilevsky
    slackrealname: "Arthur Danilevskiy"

  - jiraaccountid: 5cf3b6d098b1560e85996fae
    email: denis.kolosov@atnr.pro
    slackid: UK2CKC7SQ
    slackname: denis.kolosov
    slackrealname: "Denis Kolosov"

  - jiraaccountid: 5cde6cc64326200dc972393a
    email: denis.yudin@atnr.pro
    slackid: UJR90H205
    slackname: denis.yudin
    slackrealname: "Denis Yudin"

  - jiraaccountid: 5d2355de4b35f80c5764359b
    email: dmitrii.kishchik@atnr.pro
    slackid: UKU6CBDLJ
    slackname: dmitrii.kishchik
    slackrealname: "Dmitrii Kishchik"

  - jiraaccountid: 5bbfa4db57736d0c18e318b3
    email: galinaluppa@gmail.com
    slackid: empty
    slackname: empty
    slackrealname: empty

  - jiraaccountid: 5cc0cad796f23e0e77176afd
    email: gleb.dmitriev@atnr.pro
    slackid: UJ3JDHKPA
    slackname: gleb.dmitriev
    slackrealname: Gleb

  - jiraaccountid: 5cfd562c515e2c0c5cfb40cc
    email: irina.glebova@atnr.pro
    slackid: UK9C07RB6
    slackname: irina.glebova
    slackrealname: "Irina Glebova"

  - jiraaccountid: "557058:f48a92cd-bcb3-443e-ae4f-74e986e02d18"
    email: tiabc.work@gmail.com
    slackid: U891K2Z2P
    slackname: tiabc.work
    slackrealname: "Ivan Tomilov"

  - jiraaccountid: 5c625e3cff6a2e4d3d1460a1
    email: muzafar.muradov@atnr.pro
    slackid: UG47GFL92
    slackname: muzafar.muradov
    slackrealname: "Muzafar Muradov"

  - jiraaccountid: 5c667d34f8bb515c2c454660
    email: mary.yadykina@atnr.pro
    slackid: UFQ0NSFPZ
    slackname: mary.yadykina
    slackrealname: "Mary Yadykina"

  - jiraaccountid: "557058:0eed2b63-6426-46c4-bae1-38d9acc022e9"
    email: oleg.raev@atnr.pro
    slackid: U97DJLL11
    slackname: ovel87
    slackrealname: "Oleg Raev"

  - jiraaccountid: 5cab83cd1608c412138781c3
    email: olga.grigoruk@atnr.pro
    slackid: UHSG2NQT1
    slackname: olga.grigoruk
    slackrealname: "Olga Grigoruk"

  - jiraaccountid: 5a3e2ac8a847e93dd0bf8ebd
    email: pp@atnr.pro
    slackid: U89802W2Z
    slackname: torium0
    slackrealname: "Pavel Palenin"

  - jiraaccountid: "557058:36da39a7-f13b-4285-a658-90e3eeeea4b8"
    email: rg@atnr.pro
    slackid: U88K5BQAD
    slackname: hard.rese7
    slackrealname: "Rodion Golovushkin"

  - jiraaccountid: "557058:9cca305d-28f2-41c6-af4d-393b33527316"
    email: roman.vlasenko@atnr.pro
    slackid: UFNGKAYDC
    slackname: bamp94
    slackrealname: "Roman Vlasenko"

  - jiraaccountid: 5b27461fedacc156e2f37052
    email: stepan.morozov@atnr.pro
    slackid: U8A004WK0
    slackname: smorozovki0911
    slackrealname: "Stepan Morozov"

  - jiraaccountid: 5cfd562a8186a70c604243c5
    email: vadim.zaripov@atnr.pro
    slackid: UK15STKC3
    slackname: vadim.zaripov
    slackrealname: "Vadim Zaripov"

  - jiraaccountid: 5d313cbbec90090d00f4653d
    email: anastas.baranovskaya@gmail.com
    slackid: empty
    slackname: empty
    slackrealname: empty