loglevel: debug
ginport: 1234
gindebugmode: true
dailyworkersworkedtimecron: "00 00 07 * * *"
weeklyworkersworkedtimecron: "00 00 07 * * 1"
reportclosedsubtaskscron: "00 00 07 * * *"
employeesexceededtaskscron: "00 00 07 * * *"
gittoken:
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username:
    password:

slack:
  apiurl: https://slack.com/api
  backofficeappid: back-office-app
  migrationsid: migrations
  botname: Back Office Bot
  intoken: ITYgHVRVRhOIZfvDpVgCS6CM
  outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token:
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login:
    password:
  orgsid: 60470