loglevel: debug
ginport: 1234
gindebugmode: true
maxweekworkinghours: 30.0
cron:
  dailyworkersworkedtime: "00 00 07 * * *"
  weeklyworkersworkedtime: "00 00 07 * * 1"
  reportclosedsubtasks: "00 00 07 * * *"
  reportaftersecondreview: "00 00 07 * * *"
  employeesexceededtasks: "00 00 07 * * *"
  employeesexceededestimatetime: "00 00 07 * * *"
  reportslackspaceending: "00 00 07 * * *"
  reportgitmigrations: "@hourly"
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username:
    password:

bitbucket:
  apiurl: https://api.bitbucket.org/2.0
  owner: theflowglobal
  auth:
    username:
    password:

slack:
  apiurl: https://slack.com/api
  chanbackofficeapp: back-office-app
  chanmigrations: migrations
  botname: Back Office Bot
  intoken: xoxp-281270780213-532563372454-545645521588-6e70abc49c386bb1ad94465d19866188
  outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79
  totalVolume: 5.0
  restVolume: 0.0
  secret: 046b6a43f79bca89a7f9056921906b25

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: 9omAc5EjhHp7wKXfqBCunHri6jkOsn_FFCcPC8XOqZo
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login:
    password:
  orgsid: 60470