loglevel: debug
ginport: {{ backend_port }}
gindebugmode: true
dailyworkersworkedtimecron: "00 00 07 * * *"
weeklyworkersworkedtimecron: "00 00 07 * * 1"
reportclosedsubtaskscron: "00 00 07 * * *"
employeesexceededtaskscron: "00 00 07 * * *"
reportslackspaceendingcron: "00 00 07 * * *"
gittoken: {{ gitlab_token }}
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: {{ jira_login }}
    password: {{ jira_password }}

slack:
  apiurl: https://slack.com/api
  backofficeappid: back-office-app
  migrationsid: migrations
  botname: Back Office Bot
  intoken: xoxp-281270780213-532563372454-545645521588-6e70abc49c386bb1ad94465d19866188
  outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: {{ hubstaff_token }}
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login:
    password:
  orgsid: 60470