loglevel: debug
ginport: {{ backend_port }}
gindebugmode: true
maxweekworkinghours: 30.0
reports:
  dailyworkersworkedtime:
    schedule: "00 00 07 * * *"
    channel: "#work-reports"
  weeklyworkersworkedtime:
    schedule: "00 15 07 * * 1"
    channel: "#work-reports"
  reportclosedsubtasks:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  reportaftersecondreviewall:
    schedule: "@yearly"
    channel: "Ivan Tomilov"
  reportaftersecondreviewbe:
    schedule: "@yearly"
    channel: "Oleg Raev"
  reportaftersecondreviewfe:
    schedule: "@yearly"
    channel: "Rodion Golovushkin"
  employeesexceededtasks:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  employeesexceededestimatetime:
    schedule: "@yearly"
    channel: "#back-office-app"
  reportslackspaceending:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  reportgitmigrations:
    schedule: "@hourly"
    channel: "#migrations"
  reportsprintstatus:
    schedule: "00 00 05 * * MON"
    channel: "#general"
  reportclarificationissues:
    schedule: "00 00 07 * * *"
  report24hoursreviewissues:
    schedule: "00 00 06 * * *"
  reportgitansiblechanges:
    schedule: "@hourly"
    channel: "Stepan Morozov"
  dailyworkerslessworkedmessage:
    schedule: "00 00 07 * * 1-5"
    channel: "#general"
  weeklyreportoverworkedissues:
    schedule: "00 00 07 * * 1"
    channel: "Artem Efremov"

jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: {{ jira_login }}
    password: {{ jira_password }}

bitbucket:
  apiurl: https://api.bitbucket.org/2.0
  owner: theflowglobal
  auth:
    username: {{ jira_login }}
    password: {{ jira_password }}

slack:
  apiurl: https://slack.com/api
  botname: Back Office Bot
  intoken: xoxp-281270780213-532563372454-545645521588-6e70abc49c386bb1ad94465d19866188
  outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79
  totalVolume: 5.0
  restVolume: 0.0
  secret: 046b6a43f79bca89a7f9056921906b25
  employees:
    directorofcompany: U891K2Z2P
    projectmanager: U9FDU5W4D
    artdirector: U89802W2Z
    teamleaderbe: U97DJLL11
    teamleaderfe: U88K5BQAD
    beteam:
      - 'Stepan Morozov'
      - 'Arthur Danilevsky'
      - 'Roman Vlasenko'
      - 'Muzafar Muradov'
    feteam:
      - 'Andrey Solovyov'
      - 'Elena Parkacheva'
  ignorelist:
    - 'Pavel Palenin'
    - 'Oleg Raev'
    - 'Rodion Golovushkin'
    - 'Ivan Tomilov'
    - 'Former user'

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: {{ hubstaff_token }}
    apptoken: {{ hubstaff_app_token }}
    login:
    password:
  orgsid: 60470

database:
  name: {{ postgres_database }}
  host: {{ postgres_host }}
  port: {{ postgres_port }}
  user: {{ postgres_user }}
  password: {{ postgres_password }}
  enable_ssl: {{ postgres_enable_ssl }}