loglevel: debug
ginport: {{ backend_port }}
gindebugmode: true
dailyreportcrontime: "00 00 07 * * *"
weeklyreportcrontime: "00 00 07 * * *"
tasktimeexceedionreportcrontime: "@every 1h"
gittoken: {{ gitlab_token }}
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: {{ jira_login }}
    password: {{ jira_password }}

slack:
  apiurl: https://slack.com/api
  auth:
    intoken: ITYgHVRVRhOIZfvDpVgCS6CM
    outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79

  channel:
    migrationsid: migrations
    backofficeappid: back-office-app
    botname: Back Office Bot

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: {{ hubstaff_token }}
    apptoken: yWDG5mMG3yln_GaIg-P5vnvlKlWeXZC9IE9cqAuDkoQ
    login:
    password:
  orgsid: 60470