loglevel: debug
ginport: {{ backend_port }}
gindebugmode: true
cron:
  dailyworkersworkedtime: "00 00 07 * * *"
  dailyworkersworkedtimedetailed: "00 00 07 * * *"
  weeklyworkersworkedtime: "00 00 07 * * 1"
  reportclosedsubtasks: "00 00 07 * * *"
  reportaftersecondreview: "00 00 07 * * *"
  employeesexceededtasks: "00 00 07 * * *"
gittoken: {{ gitlab_token }}
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: {{ jira_login }}
    password: {{ jira_password }}

slack:
  apiurl: https://slack.com/api
  backofficeappid: back-office-app
  migrationsid: migrations
  botname: Back Office Bot
  intoken: ITYgHVRVRhOIZfvDpVgCS6CM
  outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: {{ hubstaff_token }}
    apptoken: {{ hubstaff_app_token }}
    login:
    password:
  orgsid: 60470