loglevel: debug
ginport: {{ backend_port }}
gindebugmode: true
maxweekworkinghours: 30.0
reports:
  dailyworkersworkedtime:
    schedule: "00 00 07 * * *"
    channel: "#work-reports"
  weeklyworkersworkedtime:
    schedule: "00 15 07 * * 1"
    channel: "#work-reports"
  reportclosedsubtasks:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  reportaftersecondreviewall:
    schedule: "@yearly"
    channel: "Ivan Tomilov"
  reportaftersecondreviewbe:
    schedule: "@yearly"
    channel: "Oleg Raev"
  reportaftersecondreviewfe:
    schedule: "@yearly"
    channel: "Rodion Golovushkin"
  employeesexceededtasks:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"
  reportslackspaceending:
    schedule: "@yearly"
    channel: "#back-office-app"
  reportgitmigrations:
    schedule: "@hourly"
    channel: "#migrations"
  reportsprintstatus:
    schedule: "00 00 05 * * MON"
    channel: "#general"
  reportclarificationissues:
    schedule: "00 00 07 * * *"
  report24hoursreviewissues:
    schedule: "00 00 07 * * *"
  reportgitansiblechanges:
    schedule: "@hourly"
    channel: "Denis Yudin"
  dailyworkerslessworkedmessage:
    schedule: "00 00 07 * * 1-5"
    channel: "#managers"
  weeklyreportoverworkedissues:
    schedule: "00 00 07 * * 1"
    channel: "Artem Efremov"
  reportepicclosedissues:
    schedule: "00 00 07 * * *"
    channel: "#back-office-app"

jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: {{ jira_login }}
    password: {{ jira_password }}

bitbucket:
  apiurl: https://api.bitbucket.org/2.0
  owner: theflowglobal
  auth:
    username: {{ jira_login }}
    password: {{ jira_password }}

slack:
  apiurl: https://slack.com/api
  botname: Back Office Bot
  intoken: {{ slack_intoken }}
  outtoken: {{ slack_outtoken }}
  totalVolume: 5.0
  restVolume: 0.0
  secret: {{ slack_secret }}
  employees:
    directorofcompany: U891K2Z2P
    projectmanager: U9FDU5W4D
    artdirector: U89802W2Z
    teamleaderbe: U97DJLL11
    teamleaderfe: U88K5BQAD
    beteam:
      - 'Morozov Stepan'
      - 'Arthur Danilevskiy'
      - 'Roman Vlasenko'
      - 'Muzafar Muradov'
    feteam:
      - 'Andrey Solovyov'
      - 'Elena Parkacheva'
  ignorelist:
    - 'Pavel Palenin'
    - 'Oleg Raev'
    - 'Rodion Golovushkin'
    - 'Ivan Tomilov'
    - 'Former user'

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: {{ hubstaff_token }}
    apptoken: {{ hubstaff_app_token }}
    login:
    password:
  orgsid: 60470

database:
  name: {{ postgres_database }}
  host: {{ postgres_host }}
  port: {{ postgres_port }}
  user: {{ postgres_user }}
  password: {{ postgres_password }}
  enable_ssl: {{ postgres_enable_ssl }}

amplify:
  notifychannelid: CKBT66G5A
  channelstag: '#cdto-staging'
  channelprod: '#cdto'
  mention:
    - U97DJLL11
    - UG47GFL92
    - U9FDU5W4D