loglevel: debug
ginport: {{ backend_port }}
gindebugmode: true
cron:
  dailyworkersworkedtime: "00 00 07 * * *"
  weeklyworkersworkedtime: "00 00 07 * * 1"
  reportclosedsubtasks: "00 00 07 * * *"
  reportaftersecondreview: "00 00 07 * * *"
  employeesexceededtasks: "00 00 07 * * *"
  employeesexceededestimatetime: "00 00 07 * * *"
  reportslackspaceending: "00 00 07 * * *"
  reportgitmigrations: "@hourly"
  reportsprintstatus: "00 00 05 * * MON"
jira:
  apiurl: https://theflow.atlassian.net
  auth:
    username: {{ jira_login }}
    password: {{ jira_password }}

bitbucket:
  apiurl: https://api.bitbucket.org/2.0
  owner: theflowglobal
  auth:
    username: {{ jira_login }}
    password: {{ jira_password }}

slack:
  apiurl: https://slack.com/api
  channels:
    general: general
    backofficeapp: back-office-app
    migrations: migrations
  botname: Back Office Bot
  projectmanager: U9FDU5W4D
  intoken: xoxp-281270780213-532563372454-545645521588-6e70abc49c386bb1ad94465d19866188
  outtoken: xoxb-281270780213-431653228886-P89rKXUXZwXyvg0gmBLI3W79
  totalVolume: 5.0
  restVolume: 0.0
  ignorelist: [Pavel Palenin, Oleg Raev, Rodion Golovushkin, Ivan Tomilov]

hubstaff:
  apiurl: https://api.hubstaff.com
  auth:
    token: {{ hubstaff_token }}
    apptoken: {{ hubstaff_app_token }}
    login:
    password:
  orgsid: 60470